---
- name: dumitrescu.ie AWS config
  hosts: localhost
  gather_facts: False
  vars:
    domain: dumitrescu.ie
    # this_zone_id: Z09633892RYPSXKOMBB3F
    s3_website_zone_id: Z1BKCTXD74EZPE # TODO: Get it with query
    region: eu-west-1
  tasks:
    - name: Get dumitrescu zone id
      community.aws.route53_zone:
        zone: dumitrescu.ie
      register: dumitrescu_route53_info
    - name: S3 Bucket / {{site}}
      vars:
        - site: "{{ domain }}"
      amazon.aws.s3_bucket:
        name: "{{ site }}"
        state: present
        policy: "{{lookup('template','bucket-policy.json.j2')}}"
    - name: S3 Bucket / {{site}}
      vars:
        - site: "www.{{ domain }}"
      amazon.aws.s3_bucket:
        name: "{{ site }}"
        state: present
        policy: "{{lookup('template','bucket-policy.json.j2')}}"
    - name: S3 Bucket / {{site}}
      vars:
        - site: "dev.{{ domain }}"
      amazon.aws.s3_bucket:
        name: "{{ site }}"
        state: present
        policy: "{{lookup('template','bucket-policy.json.j2')}}"
    - name: S3 Website / {{site}}
      vars:
        - site: "{{domain}}"
      community.aws.s3_website:
        name: "{{site}}"
        state: present
        suffix: index.html
    - name: S3 Website / {{site}}
      vars:
        - site: "dev.{{domain}}"
      community.aws.s3_website:
        name: "{{site}}"
        state: present
        suffix: index.html
    - name: S3 Website / {{site}}
      vars:
        - site: "www.{{domain}}"
      community.aws.s3_website:
        name: "{{site}}"
        state: present
        redirect_all_requests: "{{domain}}"
    - community.aws.route53:
        record: "{{domain}}"
        type: A
        value: "s3-website-{{region}}.amazonaws.com."
        alias: true
        state: present
        zone: "{{domain}}"
        alias_hosted_zone_id: "{{s3_website_zone_id}}"
        overwrite: true
    - community.aws.route53_zone:
        zone: "{{domain}}"
    - community.aws.route53:
        record: "www.{{domain}}"
        type: A
        value: "s3-website-{{region}}.amazonaws.com."
        alias: true
        state: present
        zone: "{{domain}}"
        alias_hosted_zone_id: "{{s3_website_zone_id}}"
        overwrite: true
    - community.aws.route53:
        record: "dev.{{domain}}"
        type: A
        value: "s3-website-{{region}}.amazonaws.com."
        alias: true
        state: present
        zone: "{{domain}}"
        alias_hosted_zone_id: "{{s3_website_zone_id}}"
        overwrite: true
